import type { Activity as PrismaActivity } from "@prisma/client";
import { Activity } from "@/domain/activities/enterprise/entities/activity";
import { UniqueEntityID } from "@/core/unique-entity-id";

export class ActivityMapper {
  static toDomain(raw: PrismaActivity): Activity {
    return Activity.create(
      {
        ownerId: raw.ownerId,
        type: raw.type,
        subject: raw.subject,
        description: raw.description ?? undefined,
        dueDate: raw.dueDate ?? undefined,
        completed: raw.completed,
        completedAt: raw.completedAt ?? undefined,
        failedAt: raw.failedAt ?? undefined,
        failReason: raw.failReason ?? undefined,
        skippedAt: raw.skippedAt ?? undefined,
        skipReason: raw.skipReason ?? undefined,
        dealId: raw.dealId ?? undefined,
        additionalDealIds: raw.additionalDealIds ?? undefined,
        contactId: raw.contactId ?? undefined,
        contactIds: raw.contactIds ?? undefined,
        leadContactIds: raw.leadContactIds ?? undefined,
        leadId: raw.leadId ?? undefined,
        partnerId: raw.partnerId ?? undefined,
        gotoCallId: raw.gotoCallId ?? undefined,
        gotoRecordingId: raw.gotoRecordingId ?? undefined,
        gotoRecordingDriveId: raw.gotoRecordingDriveId ?? undefined,
        gotoRecordingUrl: raw.gotoRecordingUrl ?? undefined,
        gotoRecordingUrl2: raw.gotoRecordingUrl2 ?? undefined,
        gotoTranscriptionJobId: raw.gotoTranscriptionJobId ?? undefined,
        gotoTranscriptionJobId2: raw.gotoTranscriptionJobId2 ?? undefined,
        gotoTranscriptText: raw.gotoTranscriptText ?? undefined,
        gotoCallOutcome: raw.gotoCallOutcome ?? undefined,
        gotoDuration: raw.gotoDuration ?? undefined,
        callContactType: raw.callContactType ?? undefined,
        meetingNoShow: raw.meetingNoShow,
        emailMessageId: raw.emailMessageId ?? undefined,
        emailThreadId: raw.emailThreadId ?? undefined,
        emailSubject: raw.emailSubject ?? undefined,
        emailFromAddress: raw.emailFromAddress ?? undefined,
        emailFromName: raw.emailFromName ?? undefined,
        emailReplied: raw.emailReplied,
        emailTrackingToken: raw.emailTrackingToken ?? undefined,
        emailOpenCount: raw.emailOpenCount,
        emailOpenedAt: raw.emailOpenedAt ?? undefined,
        emailLastOpenedAt: raw.emailLastOpenedAt ?? undefined,
        emailLinkClickCount: raw.emailLinkClickCount,
        emailLinkClickedAt: raw.emailLinkClickedAt ?? undefined,
        emailLastLinkClickedAt: raw.emailLastLinkClickedAt ?? undefined,
        createdAt: raw.createdAt,
        updatedAt: raw.updatedAt,
      },
      new UniqueEntityID(raw.id),
    );
  }

  static toPrisma(activity: Activity): PrismaActivity {
    return {
      id: activity.id.toString(),
      ownerId: activity.ownerId,
      type: activity.type,
      subject: activity.subject,
      description: activity.description ?? null,
      dueDate: activity.dueDate ?? null,
      completed: activity.completed,
      completedAt: activity.completedAt ?? null,
      failedAt: activity.failedAt ?? null,
      failReason: activity.failReason ?? null,
      skippedAt: activity.skippedAt ?? null,
      skipReason: activity.skipReason ?? null,
      dealId: activity.dealId ?? null,
      additionalDealIds: activity.additionalDealIds ?? null,
      contactId: activity.contactId ?? null,
      contactIds: activity.contactIds ?? null,
      leadContactIds: activity.leadContactIds ?? null,
      leadId: activity.leadId ?? null,
      partnerId: activity.partnerId ?? null,
      gotoCallId: activity.gotoCallId ?? null,
      gotoRecordingId: activity.gotoRecordingId ?? null,
      gotoRecordingDriveId: activity.gotoRecordingDriveId ?? null,
      gotoRecordingUrl: activity.gotoRecordingUrl ?? null,
      gotoRecordingUrl2: activity.gotoRecordingUrl2 ?? null,
      gotoTranscriptionJobId: activity.gotoTranscriptionJobId ?? null,
      gotoTranscriptionJobId2: activity.gotoTranscriptionJobId2 ?? null,
      gotoTranscriptText: activity.gotoTranscriptText ?? null,
      gotoCallOutcome: activity.gotoCallOutcome ?? null,
      gotoDuration: activity.gotoDuration ?? null,
      callContactType: activity.callContactType ?? null,
      meetingNoShow: activity.meetingNoShow,
      emailMessageId: activity.emailMessageId ?? null,
      emailThreadId: activity.emailThreadId ?? null,
      emailSubject: activity.emailSubject ?? null,
      emailFromAddress: activity.emailFromAddress ?? null,
      emailFromName: activity.emailFromName ?? null,
      emailReplied: activity.emailReplied,
      emailTrackingToken: activity.emailTrackingToken ?? null,
      emailOpenCount: activity.emailOpenCount,
      emailOpenedAt: activity.emailOpenedAt ?? null,
      emailLastOpenedAt: activity.emailLastOpenedAt ?? null,
      emailLinkClickCount: activity.emailLinkClickCount,
      emailLinkClickedAt: activity.emailLinkClickedAt ?? null,
      emailLastLinkClickedAt: activity.emailLastLinkClickedAt ?? null,
      createdAt: activity.createdAt,
      updatedAt: activity.updatedAt,
    };
  }
}
