import type { Activity } from "./activity";

export interface LeadContact {
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  role: string | null;
  isArchived?: boolean;
  isPrimary: boolean;
  isActive: boolean;
  whatsapp: string | null;
  linkedin: string | null;
  instagram: string | null;
  languages: string | null;
}

export interface Lead {
  id: string;
  businessName: string;
  registeredName?: string | null;
  companyRegistrationID?: string | null;
  foundationDate?: string | null;
  description?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  whatsappVerifiedAt?: string | null;
  whatsappVerifiedNumber?: string | null;
  whatsappVerified?: boolean;
  email?: string | null;
  website?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  status: string;
  quality?: string | null;
  isArchived: boolean;
  archivedAt?: string | null;
  archivedReason?: string | null;
  convertedAt?: string | null;
  inOperationsAt?: string | null;
  labels?: { id: string; name: string; color: string }[];
  leadContacts?: LeadContact[];
  convertedOrganization?: { id: string; name: string } | null;
  owner?: { id: string; name: string; email?: string | null } | null;
  vicinity?: string | null;
  zipCode?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  facebook?: string | null;
  twitter?: string | null;
  tiktok?: string | null;
  primaryActivity?: string | null;
  secondaryActivities?: string | null;
  category?: string | null;
  radius?: number | null;
  source?: string | null;
  googleId?: string | null;
  categories?: string | null;
  rating?: number | null;
  priceLevel?: number | null;
  userRatingsTotal?: number | null;
  permanentlyClosed?: boolean;
  types?: string | null;
  companyOwner?: string | null;
  companySize?: string | null;
  revenue?: number | null;
  employeesCount?: number | null;
  equityCapital?: number | null;
  businessStatus?: string | null;
  primaryCNAEId?: string | null;
  primaryCNAE?: { id: string; code: string; description: string } | null;
  internationalActivity?: string | null;
  languages?: string | null;
  socialMedia?: string | null;
  metaAds?: string | null;
  googleAds?: string | null;
  searchTerm?: string | null;
  activities?: Activity[];
  activityOrder?: string | null;
}
