import type { Organization as PrismaOrganization } from "@prisma/client";
import { Organization } from "@/domain/organizations/enterprise/entities/organization";
import { UniqueEntityID } from "@/core/unique-entity-id";

function toDate(value: unknown): Date | undefined {
  if (!value) return undefined;
  if (value instanceof Date) return value;
  if (typeof value === "string") return new Date(value);
  return undefined;
}

function toJsonString(value: unknown): string | null {
  if (value === null || value === undefined) return null;
  if (typeof value === "string") return value;
  return JSON.stringify(value);
}

export class OrganizationMapper {
  static toDomain(raw: PrismaOrganization): Organization {
    return Organization.create(
      {
        ownerId: raw.ownerId,
        name: raw.name,
        legalName: raw.legalName ?? undefined,
        foundationDate: raw.foundationDate ?? undefined,
        activityOrder: raw.activityOrder ?? undefined,
        agentResearchAt: raw.agentResearchAt ?? undefined,
        agentSummary: raw.agentSummary ?? undefined,
        agentUpdatedFields: raw.agentUpdatedFields ?? undefined,
        businessStatus: raw.businessStatus ?? undefined,
        categories: raw.categories ?? undefined,
        category: raw.category ?? undefined,
        emailVerificationReason: raw.emailVerificationReason ?? undefined,
        emailVerificationStatus: raw.emailVerificationStatus ?? undefined,
        emailVerified: raw.emailVerified ?? undefined,
        emailVerifiedAt: raw.emailVerifiedAt ?? undefined,
        equityCapital: raw.equityCapital ?? undefined,
        fieldsFilled: raw.fieldsFilled ?? undefined,
        googleAds: raw.googleAds ?? undefined,
        googleId: raw.googleId ?? undefined,
        googleMapsUrl: raw.googleMapsUrl ?? undefined,
        isProspect: raw.isProspect ?? undefined,
        latitude: raw.latitude ?? undefined,
        longitude: raw.longitude ?? undefined,
        metaAds: raw.metaAds ?? undefined,
        notes: raw.notes ?? undefined,
        openingHours: raw.openingHours ?? undefined,
        permanentlyClosed: raw.permanentlyClosed ?? undefined,
        phone2Type: raw.phone2Type ?? undefined,
        phone2Valid: raw.phone2Valid ?? undefined,
        phoneType: raw.phoneType ?? undefined,
        phoneValid: raw.phoneValid ?? undefined,
        priceLevel: raw.priceLevel ?? undefined,
        quality: raw.quality ?? undefined,
        radius: raw.radius ?? undefined,
        rating: raw.rating ?? undefined,
        searchTerm: raw.searchTerm ?? undefined,
        socialMedia: raw.socialMedia ?? undefined,
        source: raw.source ?? undefined,
        starRating: raw.starRating ?? undefined,
        status: raw.status ?? undefined,
        types: raw.types ?? undefined,
        userRatingsTotal: raw.userRatingsTotal ?? undefined,
        vicinity: raw.vicinity ?? undefined,
        whatsappPhoneType: raw.whatsappPhoneType ?? undefined,
        whatsappPhoneValid: raw.whatsappPhoneValid ?? undefined,
        whatsappVerified: raw.whatsappVerified ?? undefined,
        whatsappVerifiedAt: raw.whatsappVerifiedAt ?? undefined,
        whatsappVerifiedNumber: raw.whatsappVerifiedNumber ?? undefined,
        website: raw.website ?? undefined,
        phone: raw.phone ?? undefined,
        whatsapp: raw.whatsapp ?? undefined,
        email: raw.email ?? undefined,
        country: raw.country ?? undefined,
        state: raw.state ?? undefined,
        city: raw.city ?? undefined,
        zipCode: raw.zipCode ?? undefined,
        streetAddress: raw.streetAddress ?? undefined,
        industry: raw.industry ?? undefined,
        employeeCount: raw.employeeCount ?? undefined,
        annualRevenue: raw.annualRevenue ?? undefined,
        taxId: raw.taxId ?? undefined,
        description: raw.description ?? undefined,
        companyOwner: raw.companyOwner ?? undefined,
        companySize: raw.companySize ?? undefined,
        languages: raw.languages ?? undefined,
        commLanguage: raw.commLanguage,
        primaryCNAEId: raw.primaryCNAEId ?? undefined,
        internationalActivity: raw.internationalActivity ?? undefined,
        instagram: raw.instagram ?? undefined,
        linkedin: raw.linkedin ?? undefined,
        facebook: raw.facebook ?? undefined,
        twitter: raw.twitter ?? undefined,
        tiktok: raw.tiktok ?? undefined,
        sourceLeadId: raw.sourceLeadId ?? undefined,
        referredByPartnerId: raw.referredByPartnerId ?? undefined,
        externalProjectIds: raw.externalProjectIds ?? undefined,
        driveFolderId: raw.driveFolderId ?? undefined,
        hasHosting: raw.hasHosting,
        hostingRenewalDate: raw.hostingRenewalDate ?? undefined,
        hostingPlan: raw.hostingPlan ?? undefined,
        hostingValue: raw.hostingValue ?? undefined,
        hostingReminderDays: raw.hostingReminderDays,
        hostingNotes: raw.hostingNotes ?? undefined,
        inOperationsAt: raw.inOperationsAt ?? undefined,
        segment: (raw as Record<string, unknown>).segment as string | undefined ?? undefined,
        legalNature: (raw as Record<string, unknown>).legalNature as string | undefined ?? undefined,
        branchType: (raw as Record<string, unknown>).branchType as string | undefined ?? undefined,
        simplesNacional: (raw as Record<string, unknown>).simplesNacional as boolean | undefined ?? undefined,
        isMei: (raw as Record<string, unknown>).isMei as boolean | undefined ?? undefined,
        revenueRange: (raw as Record<string, unknown>).revenueRange as string | undefined ?? undefined,
        phone2: (raw as Record<string, unknown>).phone2 as string | undefined ?? undefined,
        sourceGroup: (raw as Record<string, unknown>).sourceGroup as string | undefined ?? undefined,
        createdAt: raw.createdAt,
        updatedAt: raw.updatedAt,
      },
      new UniqueEntityID(raw.id),
    );
  }

  static toPrisma(organization: Organization): Omit<PrismaOrganization, never> {
    return {
      id: organization.id.toString(),
      ownerId: organization.ownerId,
      name: organization.name,
      legalName: organization.legalName ?? null,
      activityOrder: organization.activityOrder ?? null,
      agentResearchAt: organization.agentResearchAt ?? null,
      agentSummary: organization.agentSummary ?? null,
      agentUpdatedFields: organization.agentUpdatedFields ?? null,
      businessStatus: organization.businessStatus ?? null,
      categories: organization.categories ?? null,
      category: organization.category ?? null,
      emailVerificationReason: organization.emailVerificationReason ?? null,
      emailVerificationStatus: organization.emailVerificationStatus ?? null,
      emailVerified: organization.emailVerified ?? null,
      emailVerifiedAt: organization.emailVerifiedAt ?? null,
      equityCapital: organization.equityCapital ?? null,
      fieldsFilled: organization.fieldsFilled ?? null,
      googleAds: organization.googleAds ?? null,
      googleId: organization.googleId ?? null,
      googleMapsUrl: organization.googleMapsUrl ?? null,
      latitude: organization.latitude ?? null,
      longitude: organization.longitude ?? null,
      metaAds: organization.metaAds ?? null,
      notes: organization.notes ?? null,
      openingHours: organization.openingHours ?? null,
      phone2Type: organization.phone2Type ?? null,
      phone2Valid: organization.phone2Valid ?? null,
      phoneType: organization.phoneType ?? null,
      phoneValid: organization.phoneValid ?? null,
      priceLevel: organization.priceLevel ?? null,
      quality: organization.quality ?? null,
      radius: organization.radius ?? null,
      rating: organization.rating ?? null,
      searchTerm: organization.searchTerm ?? null,
      socialMedia: organization.socialMedia ?? null,
      source: organization.source ?? null,
      starRating: organization.starRating ?? null,
      status: organization.status ?? null,
      types: organization.types ?? null,
      userRatingsTotal: organization.userRatingsTotal ?? null,
      vicinity: organization.vicinity ?? null,
      whatsappPhoneType: organization.whatsappPhoneType ?? null,
      whatsappPhoneValid: organization.whatsappPhoneValid ?? null,
      whatsappVerifiedAt: organization.whatsappVerifiedAt ?? null,
      whatsappVerifiedNumber: organization.whatsappVerifiedNumber ?? null,
      isProspect: organization.isProspect ?? false,
      permanentlyClosed: organization.permanentlyClosed ?? false,
      whatsappVerified: organization.whatsappVerified ?? false,
      foundationDate: organization.foundationDate instanceof Date
        ? organization.foundationDate
        : organization.foundationDate
          ? new Date(organization.foundationDate as string)
          : null,
      website: organization.website ?? null,
      phone: organization.phone ?? null,
      whatsapp: organization.whatsapp ?? null,
      email: organization.email ?? null,
      country: organization.country ?? null,
      state: organization.state ?? null,
      city: organization.city ?? null,
      zipCode: organization.zipCode ?? null,
      streetAddress: organization.streetAddress ?? null,
      industry: organization.industry ?? null,
      employeeCount: organization.employeeCount ?? null,
      annualRevenue: organization.annualRevenue ?? null,
      taxId: organization.taxId ?? null,
      description: organization.description ?? null,
      companyOwner: organization.companyOwner ?? null,
      companySize: organization.companySize ?? null,
      languages: toJsonString(organization.languages),
      commLanguage: organization.commLanguage,
      primaryCNAEId: organization.primaryCNAEId ?? null,
      internationalActivity: organization.internationalActivity ?? null,
      instagram: organization.instagram ?? null,
      linkedin: organization.linkedin ?? null,
      facebook: organization.facebook ?? null,
      twitter: organization.twitter ?? null,
      tiktok: organization.tiktok ?? null,
      sourceLeadId: organization.sourceLeadId ?? null,
      referredByPartnerId: organization.referredByPartnerId ?? null,
      externalProjectIds: toJsonString(organization.externalProjectIds),
      driveFolderId: organization.driveFolderId ?? null,
      hasHosting: organization.hasHosting,
      hostingRenewalDate: organization.hostingRenewalDate instanceof Date
        ? organization.hostingRenewalDate
        : organization.hostingRenewalDate
          ? new Date(organization.hostingRenewalDate as string)
          : null,
      hostingPlan: organization.hostingPlan ?? null,
      hostingValue: organization.hostingValue ?? null,
      hostingReminderDays: organization.hostingReminderDays,
      hostingNotes: organization.hostingNotes ?? null,
      inOperationsAt: organization.inOperationsAt instanceof Date
        ? organization.inOperationsAt
        : organization.inOperationsAt
          ? new Date(organization.inOperationsAt as string)
          : null,
      segment: organization.segment ?? null,
      legalNature: organization.legalNature ?? null,
      branchType: organization.branchType ?? null,
      simplesNacional: organization.simplesNacional ?? null,
      isMei: organization.isMei ?? null,
      revenueRange: organization.revenueRange ?? null,
      phone2: organization.phone2 ?? null,
      sourceGroup: organization.sourceGroup ?? null,
      createdAt: organization.createdAt,
      updatedAt: organization.updatedAt,
    } as PrismaOrganization;
  }
}
