ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "revenueRange" TEXT;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "segment" TEXT;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "legalNature" TEXT;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "branchType" TEXT;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "simplesNacional" BOOLEAN;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "isMei" BOOLEAN;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "phone2" TEXT;
